(function() {var implementors = {};
implementors["embree_rs"] = [{text:"impl&lt;'a, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"embree_rs/buffer/struct.Buffer.html\" title=\"struct embree_rs::buffer::Buffer\">Buffer</a>&lt;'a, T&gt;",synthetic:false,types:["embree_rs::buffer::Buffer"]},{text:"impl&lt;'a, T:&nbsp;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"embree_rs/buffer/struct.MappedBuffer.html\" title=\"struct embree_rs::buffer::MappedBuffer\">MappedBuffer</a>&lt;'a, T&gt;",synthetic:false,types:["embree_rs::buffer::MappedBuffer"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"embree_rs/device/struct.Device.html\" title=\"struct embree_rs::device::Device\">Device</a>",synthetic:false,types:["embree_rs::device::Device"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"enum\" href=\"embree_rs/geometry/enum.Geometry.html\" title=\"enum embree_rs::geometry::Geometry\">Geometry</a>&lt;'a&gt;",synthetic:false,types:["embree_rs::geometry::Geometry"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"embree_rs/scene/struct.Scene.html\" title=\"struct embree_rs::scene::Scene\">Scene</a>&lt;'a&gt;",synthetic:false,types:["embree_rs::scene::Scene"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
